const indicators = [
    'Full Year GDP Growth',
    'GDP',
    'GDP Aggregate Demand QoQ',
    'GDP Aggregate Demand YoY',
    'GDP Annual Growth Rate',
    'GDP Constant Prices',
    'GDP External Demand Contribution',
    'GDP from Agriculture',
    'GDP from Construction',
    'GDP from Manufacturing',
    'GDP from Mining',
    'GDP from Public Administration',
    'GDP from Services',
    'GDP from Transport',
    'GDP from Utilities',
    'GDP Growth Annualized',
    'GDP Growth Non Oil Sector',
    'GDP Growth Oil Sector',
    'GDP Growth Rate',
    'GDP per Capita',
    'GDP per Capita PPP',
    'GDP Sales QoQ',
    'Gross Fixed Capital Formation',
    'Gross National Product',
    'Monthly GDP MoM',
    'Monthly GDP YoY',
    'Real Consumer Spending',
    'Weekly Economic Index',
]

module.exports = indicators;